# Generated by Django 4.2 on 2023-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkHorizon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='imagen',
            field=models.FileField(default='', upload_to='sparkHorizon/imagen/'),
            preserve_default=False,
        ),
    ]
