# Generated by Django 4.2 on 2023-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkHorizon', '0002_teammember_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='portada',
            field=models.FileField(upload_to=''),
        ),
    ]
